let timelineElements = [
    {
        id: 1,
        title: "Netcentric",
        location: "Berlin, Germany",
        isWorkIcon: "work",
        role: "Frontend Software Engineer",
        description: "Frontend development of different kinds of projects. Technologies used include Javascript, HTML/HTL, CSS/SCSS, Adobe Experience Manager, Git.",
        date: "Mar 2022 - Present",
        bgColor: { background: "rgba(255, 255, 255, 0.15)" },
        icon: "netcentric",        
    },
    {
        id: 2,
        title: "Talkdesk",
        location: "Lisbon, Portugal",
        isWorkIcon: "work",
        role: "Fullstack Software Engineer",
        description: "Development of the digital communication channels solutions like SMS, Live Chat, Email. Technologies used include Kotlin, Spring, Javascript, React, Ruby, Postgres, Docker, Git.",
        date: "Jan 2021 - Feb 2022",
        bgColor: { background: "rgba(255, 255, 255, 0.15)" },
        icon: "talkdesk",        
    },
    {
        id: 3,
        title: "Instituto Superior Técnico",
        location: "Lisbon, Portugal",
        isWorkIcon: "school",
        role: "MSc in Information Systems and Computer Engineering",
        grade: "Thesis grade: 20/20 | Final grade: 18/20",
        description: "Specialized in Game Development",
        date: "Sep 2018 - Jan 2021",
        bgColor: { background: "rgba(255, 255, 255, 0.15)" },
        icon: "ist",        
    },
    {
        id: 4,
        title: "Aalto University",
        location: "Helsinki, Finland",
        isWorkIcon: "school",
        role: "MSc in Computer Science - Erasmus Program",
        description: "One semester abroad",
        date: "Sep 2019 - Dec 2019",
        bgColor: { 
            background: "rgba(255, 255, 255, 0.15)",
        },
        icon: "aalto",        
    },
    {
        id: 5,
        title: "ISCTE-IUL",
        location: "Lisbon, Portugal",
        isWorkIcon: "school",
        role: "BSc in Information Systems and Computer Engineering",
        grade: "Final grade: 15/20",
        description: '',
        date: "Sep 2015 - Jun 2018",
        bgColor: { background: "rgba(255, 255, 255, 0.15)" },
        icon: "iscte",        
    }
]

export default timelineElements